In [1]:
from mindspore import Tensor,ops
import mindspore

In [2]:
img:Tensor=ops.ones((1,3,512,512),mindspore.dtype.float64)
print(img.shape)

(1, 3, 512, 512)


In [4]:
print(img[:,:,1:,:].shape)

(1, 3, 511, 512)


In [38]:
out=VGG(img)
print(img.shape)

NameError: name 'VGG' is not defined

In [6]:
m=Tensor([[[0,1,2,3,4],[5,6,7,8,9]],[[0,1,2,3,4],[5,6,7,8,9]]])

In [7]:
print(m.reshape(-1,m.shape[-1]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
from mindspore import Tensor, Parameter, ops
from mindspore.ops.operations.image_ops import ResizeBilinearV2
import numpy as np

In [29]:
x = Tensor([[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]]], mindspore.float32)
rv= ResizeBilinearV2()
output = rv(x, (6, 5))
out=output[0][0]
print(out)

[[ 1.         2.         3.         4.         5.       ]
 [ 2.6666667  3.6666667  4.666667   5.666667   6.666667 ]
 [ 4.3333335  5.3333335  6.3333335  7.3333335  8.333334 ]
 [ 6.         7.         8.         9.        10.       ]
 [ 6.         7.         8.         9.        10.       ]
 [ 6.         7.         8.         9.        10.       ]]
